(defproject react-cljs "0.1.0"
  :dependencies [[thheller/shadow-cljs "2.12.5"]
                 [org.clojure/clojure "1.10.3"]
                 [org.clojure/clojurescript "1.10.844"]
                 [appliedscience/js-interop "0.2.5"]
                 [binaryage/devtools "1.0.3"]
                 [binaryage/oops "0.7.1"]
                 [com.fulcrologic/guardrails "1.1.4" :exclusions [com.taoensso/encore]]
                 [com.wsscode/edn-json "1.1.0"]
                 [datascript "1.0.7"]
                 [funcool/cuerdas "2020.03.26-3"]
                 [funcool/httpurr "2.0.0"]
                 [funcool/okulary "2020.04.14-0"]
                 [funcool/promesa "6.0.0"]
                 [funcool/rumext "2021.01.26-0"]
                 [net.sekao/odoyle-rules "0.8.0"]]

  :source-paths ["src"]
  :resource-paths ["dev-resources" "resources"]
  :target-path "target/%s")
